name: p2p
description: "Peer-to-peer networking layout for LocalSend"
version: 0.0.1
publish_to: "none"

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  common:
    path: ../common
  flutter_rust_bridge: 2.11.1
  # Networking dependencies from app
  rhttp: 0.13.0
  refena_flutter: 3.2.0
  uri_content: 3.1.1
  connectivity_plus: 6.1.0
  network_info_plus: 6.1.1
  uuid: 4.5.1
  logging: 1.3.0
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  device_info_plus: ^11.1.1
  collection: ^1.17.2
  basic_utils: ^5.7.0
  wechat_assets_picker: ^9.0.0

dev_dependencies:
  ffi: ^2.0.2
  ffigen: ^11.0.0
  flutter_lints: ^2.0.0
  build_runner: 2.7.1
  dart_mappable_builder: 4.6.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      linux:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      windows:
        ffiPlugin: true

  assets:
    - assets/web/
